"""Public machine-learning APIs for leakage-safe baseline predictions."""

from .evaluation import (
    EvaluationError,
    TemporalSplit,
    WalkForwardFold,
    chronological_split,
    evaluate_counts,
    evaluate_goal_counts,
    evaluate_match_results,
    expected_calibration_error,
    walk_forward_splits,
)
from .features import (
    FeatureBuildResult,
    FeatureBuilder,
    FeatureEngineeringError,
    PrematchFeatureBuilder,
    TemporalLeakageError,
    TimeAwareFeatureBuilder,
    assert_no_temporal_leakage,
    build_prematch_features,
)
from .poisson import (
    ExplanationFactor,
    InsufficientFeatureDataError,
    LambdaEstimate,
    PoissonBaseline,
    PoissonModelError,
    PoissonPrediction,
    PoissonPredictor,
    ScoreProbability,
    derive_probabilities,
    estimate_lambdas_from_features,
    poisson_score_matrix,
    predict_match,
)
from .training import (
    DependencyUnavailableError,
    PoissonTrainingReport,
    TrainedPoissonGoalsModel,
    TrainingError,
    TrainingMetadata,
    load_model,
    save_model,
    train_evaluate_poisson,
    train_poisson_regressors,
)
from .xgboost_model import (
    TrainedXGBoostGoalsModel,
    XGBoostTrainingReport,
    train_evaluate_xgboost,
    train_xgboost_regressors,
)


__all__ = [
    "DependencyUnavailableError",
    "EvaluationError",
    "ExplanationFactor",
    "FeatureBuildResult",
    "FeatureBuilder",
    "FeatureEngineeringError",
    "InsufficientFeatureDataError",
    "LambdaEstimate",
    "PoissonBaseline",
    "PoissonModelError",
    "PoissonPrediction",
    "PoissonPredictor",
    "PoissonTrainingReport",
    "PrematchFeatureBuilder",
    "ScoreProbability",
    "TemporalLeakageError",
    "TemporalSplit",
    "TimeAwareFeatureBuilder",
    "TrainedPoissonGoalsModel",
    "TrainingError",
    "TrainingMetadata",
    "WalkForwardFold",
    "assert_no_temporal_leakage",
    "build_prematch_features",
    "chronological_split",
    "derive_probabilities",
    "estimate_lambdas_from_features",
    "evaluate_counts",
    "evaluate_goal_counts",
    "evaluate_match_results",
    "expected_calibration_error",
    "load_model",
    "poisson_score_matrix",
    "predict_match",
    "save_model",
    "train_evaluate_poisson",
    "train_poisson_regressors",
    "train_evaluate_xgboost",
    "train_xgboost_regressors",
    "TrainedXGBoostGoalsModel",
    "XGBoostTrainingReport",
    "walk_forward_splits",
]
